imports:
  - { resource: ../common.yml }

services:
  _defaults:
    public: false
    autowire: true
    bind:
      $context: '@inpost.shipping.context'

  inpost.shipping.store.module.configuration:
    class: InPost\Shipping\Presenter\Store\Modules\ConfigurationModule

  inpost.shipping.store.module.context:
    class: InPost\Shipping\Presenter\Store\Modules\ContextModule

  inpost.shipping.store.module.organization:
    class: InPost\Shipping\Presenter\Store\Modules\OrganizationModule
    public: true

  inpost.shipping.store.module.services:
    class: InPost\Shipping\Presenter\Store\Modules\ServicesModule

  inpost.shipping.store.module.carriers:
    class: InPost\Shipping\Presenter\Store\Modules\CarriersModule

  inpost.shipping.store.presenter:
    class: InPost\Shipping\Presenter\Store\StorePresenter
    public: true
    arguments:
      $modules:
        - '@inpost.shipping.store.module.configuration'
        - '@inpost.shipping.store.module.context'
        - '@inpost.shipping.store.module.organization'
        - '@inpost.shipping.store.module.services'
        - '@inpost.shipping.store.module.carriers'

  InPost\Shipping\Translations\Translations:
    class: InPost\Shipping\Translations\Translations

  inpost.shipping.translations.validation_errors:
    class: InPost\Shipping\Translations\ValidationErrorTranslator

  InPost\Shipping\Translations\ValidationErrorTranslator: '@inpost.shipping.translations.validation_errors'

  inpost.shipping.translations.sending_method:
    class: InPost\Shipping\Translations\SendingMethodTranslator
    public: true

  InPost\Shipping\Translations\SendingMethodTranslator: '@inpost.shipping.translations.sending_method'

  inpost.shipping.translations.shipping_service:
    class: InPost\Shipping\Translations\ShippingServiceTranslator
    public: true

  InPost\Shipping\Translations\ShippingServiceTranslator: '@inpost.shipping.translations.shipping_service'

  inpost.shipping.translations.dimension_template:
    class: InPost\Shipping\Translations\DimensionTemplateTranslator
    public: true

  InPost\Shipping\Translations\DimensionTemplateTranslator: '@inpost.shipping.translations.dimension_template'

  InPost\Shipping\Translations\WeekdayTranslator:
    class: InPost\Shipping\Translations\WeekdayTranslator

  InPost\Shipping\Translations\FieldTranslator:
    class: InPost\Shipping\Translations\FieldTranslator

  inpost.shipping.presenter.carrier:
    class: InPost\Shipping\Presenter\CarrierPresenter
    public: true

  InPost\Shipping\Presenter\CarrierPresenter: '@inpost.shipping.presenter.carrier'

  InPost\Shipping\Presenter\ShipmentPresenter:
    class: InPost\Shipping\Presenter\ShipmentPresenter
    public: true

  InPost\Shipping\Presenter\ShipmentStatusPresenter:
    class: InPost\Shipping\Presenter\ShipmentStatusPresenter

  inpost.shipping.presenter.dispatch_point:
    class: InPost\Shipping\Presenter\DispatchPointPresenter
    public: true

  InPost\Shipping\Presenter\DispatchPointPresenter: '@inpost.shipping.presenter.dispatch_point'

  inpost.shipping.validator.api_configuration:
    class: InPost\Shipping\Validator\ApiConfigurationValidator
    public: true

  inpost.shipping.validator.geo_widget_configuration:
    class: InPost\Shipping\Validator\GeoWidgetConfigurationValidator
    public: true

  InPost\Shipping\Validator\AddressValidator:
    class: InPost\Shipping\Validator\AddressValidator

  inpost.shipping.validator.sender:
    class: InPost\Shipping\Validator\SenderValidator
    public: true

  inpost.shipping.validator.weekend_delivery_configuration:
    class: InPost\Shipping\Validator\WeekendDeliveryConfigurationValidator
    public: true

  InPost\Shipping\Validator\ShipmentDimensionsValidator:
    class: InPost\Shipping\Validator\ShipmentDimensionsValidator

  inpost.shipping.validator.orders_configuration:
    class: InPost\Shipping\Validator\OrdersConfigurationValidator
    public: true

  inpost.shipping.validator.google_api_key:
    class: InPost\Shipping\Validator\GoogleApiKeyValidator
    public: true

  inpost.shipping.validator.module_controllers:
    class: InPost\Shipping\Validator\ModuleControllersValidator
    public: true

  InPost\Shipping\DataProvider\OrganizationDataProvider:
    class: InPost\Shipping\DataProvider\OrganizationDataProvider

  inpost.shipping.data_provider.order_shipments:
    class: InPost\Shipping\DataProvider\OrderShipmentsDataProvider
    public: true

  InPost\Shipping\DataProvider\CarrierDataProvider:
    class: InPost\Shipping\DataProvider\CarrierDataProvider

  InPost\Shipping\DataProvider\OrderDimensionsDataProvider:
    class: InPost\Shipping\DataProvider\OrderDimensionsDataProvider

  InPost\Shipping\DataProvider\TemplateDimensionsDataProvider:
    class: InPost\Shipping\DataProvider\TemplateDimensionsDataProvider

  InPost\Shipping\ChoiceProvider\SendingMethodChoiceProvider:
    class: InPost\Shipping\ChoiceProvider\SendingMethodChoiceProvider

  InPost\Shipping\ChoiceProvider\DispatchPointChoiceProvider:
    class: InPost\Shipping\ChoiceProvider\DispatchPointChoiceProvider

  InPost\Shipping\ChoiceProvider\CarrierChoiceProvider:
    class: InPost\Shipping\ChoiceProvider\CarrierChoiceProvider

  InPost\Shipping\ChoiceProvider\ShippingServiceChoiceProvider:
    class: InPost\Shipping\ChoiceProvider\ShippingServiceChoiceProvider

  InPost\Shipping\ChoiceProvider\DimensionTemplateChoiceProvider:
    class: InPost\Shipping\ChoiceProvider\DimensionTemplateChoiceProvider

  InPost\Shipping\ChoiceProvider\WeekdayChoiceProvider:
    class: InPost\Shipping\ChoiceProvider\WeekdayChoiceProvider

  InPost\Shipping\ChoiceProvider\ShipmentLabelTypeChoiceProvider:
    class: InPost\Shipping\ChoiceProvider\ShipmentLabelTypeChoiceProvider

  InPost\Shipping\ChoiceProvider\ShipmentLabelFormatChoiceProvider:
    class: InPost\Shipping\ChoiceProvider\ShipmentLabelFormatChoiceProvider

  InPost\Shipping\ChoiceProvider\ShipmentReferenceFieldChoiceProvider:
    class: InPost\Shipping\ChoiceProvider\ShipmentReferenceFieldChoiceProvider

  InPost\Shipping\ChoiceProvider\OrderStateChoiceProvider:
    class: InPost\Shipping\ChoiceProvider\OrderStateChoiceProvider

  inpost.shipping.choice_provider.product_template:
    class: InPost\Shipping\ChoiceProvider\ProductTemplateChoiceProvider
    public: true

  InPost\Shipping\ChoiceProvider\ModuleChoiceProvider:
    class: InPost\Shipping\ChoiceProvider\ModuleChoiceProvider

  InPost\Shipping\ChoiceProvider\ModulePageChoiceProvider:
    class: InPost\Shipping\ChoiceProvider\ModulePageChoiceProvider

  inpost.shipping.install.installer:
    class: InPost\Shipping\Install\Installer
    public: true
    arguments:
      $subInstallers:
        - '@inpost.shipping.install.hooks'
        - '@inpost.shipping.install.tabs'
        - '@inpost.shipping.install.carriers'
        - '@inpost.shipping.install.database'
        - '@inpost.shipping.install.configuration'

  inpost.shipping.install.hooks:
    class: InPost\Shipping\Install\Hooks
    public: true

  InPost\Shipping\Install\Hooks:
    alias: inpost.shipping.install.hooks
    public: true

  inpost.shipping.install.tabs:
    class: InPost\Shipping\Install\Tabs

  inpost.shipping.install.database:
    class: InPost\Shipping\Install\Database
    public: false
    autowire: true

  InPost\Shipping\Install\Database:
    alias: inpost.shipping.install.database
    public: true

  inpost.shipping.install.carriers:
    class: InPost\Shipping\Install\Carriers
    public: true

  inpost.shipping.install.configuration:
    class: InPost\Shipping\Install\Configuration
    arguments:
      $configurations:
        - '@inpost.shipping.configuration.shipx'
        - '@inpost.shipping.configuration.sending'
        - '@inpost.shipping.configuration.szybkie_zwroty'
        - '@inpost.shipping.configuration.carriers'
        - '@inpost.shipping.configuration.orders'
        - '@inpost.shipping.configuration.shop'

  InPost\Shipping\CarrierUpdater:
    class: InPost\Shipping\CarrierUpdater

  InPost\Shipping\CarrierConfigurationUpdater:
    class: InPost\Shipping\CarrierConfigurationUpdater

  inpost.shipping.handler.product_update:
    class: InPost\Shipping\Handler\ProductUpdateHandler
    public: true

  InPost\Shipping\Helper\DefaultShipmentReferenceExtractor:
    class: InPost\Shipping\Helper\DefaultShipmentReferenceExtractor

  InPost\Shipping\Helper\ParcelDimensionsComparator:
    class: InPost\Shipping\Helper\ParcelDimensionsComparator

  inpost.shipping.handler.add_service:
    class: InPost\Shipping\Handler\ShippingService\AddServiceHandler
    public: true

  inpost.shipping.handler.update_service:
    class: InPost\Shipping\Handler\ShippingService\UpdateServiceHandler
    public: true

  inpost.shipping.handler.delete_service:
    class: InPost\Shipping\Handler\ShippingService\DeleteServiceHandler
    public: true

  inpost.shipping.handler.shipment.create:
    class: InPost\Shipping\Handler\Shipment\CreateShipmentHandler
    public: true

  inpost.shipping.handler.shipment.bulk_create:
    class: InPost\Shipping\Handler\Shipment\BulkCreateShipmentHandler
    public: true

  inpost.shipping.handler.dispatch_order.create:
    class: InPost\Shipping\Handler\DispatchOrder\CreateDispatchOrderHandler
    public: true

  inpost.shipping.handler.dispatch_order.update:
    class: InPost\Shipping\Handler\DispatchOrder\UpdateDispatchOrderHandler
    public: true

  InPost\Shipping\Builder\Shipment\CreateShipmentPayloadBuilder:
    class: InPost\Shipping\Builder\Shipment\CreateShipmentPayloadBuilder

  InPost\Shipping\Builder\Shipment\ParcelPayloadBuilder:
    class: InPost\Shipping\Builder\Shipment\ParcelPayloadBuilder

  InPost\Shipping\Builder\DispatchOrder\CreateDispatchOrderPayloadBuilder:
    class: InPost\Shipping\Builder\DispatchOrder\CreateDispatchOrderPayloadBuilder

  inpost.shipping.handler.shipment.print_label:
    class: InPost\Shipping\Handler\Shipment\PrintShipmentLabelHandler
    public: true

  inpost.shipping.views.modal.dispatch_order:
    class: InPost\Shipping\Views\Modal\CreateDispatchOrderModal
    public: true

  InPost\Shipping\Views\Modal\CreateDispatchOrderModal: '@inpost.shipping.views.modal.dispatch_order'

  inpost.shipping.views.modal.shipment:
    class: InPost\Shipping\Views\Modal\CreateShipmentModal
    public: true

  inpost.shipping.views.modal.shipment_details:
    class: InPost\Shipping\Views\Modal\ShipmentDetailsModal
    public: true

  inpost.shipping.views.modal.print_label:
    class: InPost\Shipping\Views\Modal\PrintShipmentLabelModal
    public: true

  inpost.shipping.views.shipment_nav_tabs:
    class: InPost\Shipping\Views\ShipmentNavTabs
    public: true

  inpost.shipping.views.dispatch_point_nav_tabs:
    class: InPost\Shipping\Views\DispatchPointNavTabs
    public: true

  inpost.shipping.views.modal.map:
    class: InPost\Shipping\Views\Modal\MapModal
    public: true

  inpost.shipping.hook_updater:
    class: InPost\Shipping\HookUpdater
    public: true
